// <auto-generated />
using System;
using Decisya.Modules.Audit.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Decisya.Modules.Audit.Infrastructure.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20261001200914_AddAuditRecords")]
    partial class AddAuditRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Decisya.Modules.Audit.Domain.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("FeatureKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("feature_key");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_audit_records_tenant_occurred");

                    b.ToTable("audit_records", "audit", t =>
                        {
                            t.HasCheckConstraint("ck_audit_records_action", "action IN ('entitlements.trial.start', 'entitlements.override.grant', 'entitlements.override.revoke')");

                            t.HasCheckConstraint("ck_audit_records_actor", "length(btrim(actor_user_id)) > 0");

                            t.HasCheckConstraint("ck_audit_records_feature_key", "(action = 'entitlements.trial.start') = (feature_key IS NULL)");

                            t.HasCheckConstraint("ck_audit_records_outcome", "outcome IN ('succeeded')");

                            t.HasCheckConstraint("ck_audit_records_trace_id", "trace_id IS NULL OR trace_id ~ '^[0-9a-f]{32}$'");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
