// <auto-generated />
using System;
using Decisya.Modules.Entitlements.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Decisya.Modules.Entitlements.Infrastructure.Migrations
{
    [DbContext(typeof(EntitlementsDbContext))]
    partial class EntitlementsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("entitlements")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Decisya.Modules.Entitlements.Domain.FeatureOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("feature_key");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "FeatureKey")
                        .IsUnique()
                        .HasDatabaseName("ux_feature_overrides_tenant_feature");

                    b.ToTable("feature_overrides", "entitlements", t =>
                        {
                            t.HasCheckConstraint("ck_feature_overrides_expiry", "expires_at IS NULL OR expires_at > granted_at");
                        });
                });

            modelBuilder.Entity("Decisya.Modules.Entitlements.Domain.TrialGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("plan");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_trial_grants_tenant");

                    b.ToTable("trial_grants", "entitlements", t =>
                        {
                            t.HasCheckConstraint("ck_trial_grants_period", "ends_at > starts_at");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
